package synth

import (
	"bytes"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"
)

var update = flag.Bool("update", false, "regenerate testdata/golden from its manifest's spec")

func TestAFixtureRoundTripsThroughDisk(t *testing.T) {
	dir := t.TempDir()
	spec := small(42)
	m, err := Write(spec, dir, false)
	if err != nil {
		t.Fatalf("Write: %v", err)
	}
	if m.Generator != Version || m.Counts.Users != 3 || m.Counts.Patients != 2 || len(m.Digests) != 3 {
		t.Errorf("manifest = %+v", m)
	}

	read, err := ReadManifest(dir)
	if err != nil {
		t.Fatalf("ReadManifest: %v", err)
	}
	if !reflect.DeepEqual(read.Spec, spec) || read.Digests[MeasurementsFile] != m.Digests[MeasurementsFile] {
		t.Error("the manifest read back differs from the one written")
	}

	want, _ := generate(t, spec)
	users, err := ReadUsers(dir)
	if err != nil || !reflect.DeepEqual(users, want.users) {
		t.Errorf("ReadUsers = %v, %v", users, err)
	}
	patients, err := ReadPatients(dir)
	if err != nil || !reflect.DeepEqual(patients, want.patients) {
		t.Errorf("ReadPatients = %v, %v", patients, err)
	}
	var got []Measurement
	if err := EachMeasurement(dir, func(x Measurement) error { got = append(got, x); return nil }); err != nil {
		t.Fatal(err)
	}
	if len(got) != len(want.measurements) {
		t.Fatalf("%d readings read back, %d generated", len(got), len(want.measurements))
	}
	for i := range got {
		if got[i].PatientReference != want.measurements[i].PatientReference || got[i].Value != want.measurements[i].Value ||
			!got[i].RecordedAt.Equal(want.measurements[i].RecordedAt) || string(got[i].Metadata) != string(want.measurements[i].Metadata) {
			t.Fatalf("reading %d differs after the round trip:\n%+v\n%+v", i, got[i], want.measurements[i])
		}
	}

	if _, err := Write(spec, dir, false); err == nil || !strings.Contains(err.Error(), "already holds a fixture") {
		t.Errorf("a second Write without overwrite must be refused, got %v", err)
	}
	if _, err := Write(spec, dir, true); err != nil {
		t.Errorf("Write with overwrite: %v", err)
	}
}

func TestATamperedOrForeignFixtureIsRefused(t *testing.T) {
	dir := t.TempDir()
	if _, err := Write(small(1), dir, false); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, MeasurementsFile)
	raw, _ := os.ReadFile(path)
	if err := os.WriteFile(path, raw[:len(raw)/2], 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := ReadManifest(dir); err == nil || !strings.Contains(err.Error(), "does not match its manifest digest") {
		t.Errorf("a truncated data file must be refused, got %v", err)
	}

	other := t.TempDir()
	if _, err := Write(small(1), other, false); err != nil {
		t.Fatal(err)
	}
	mp := filepath.Join(other, ManifestFile)
	raw, _ = os.ReadFile(mp)
	raw = bytes.Replace(raw, []byte(`"generator": "`+Version+`"`), []byte(`"generator": "0"`), 1)
	if err := os.WriteFile(mp, raw, 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := ReadManifest(other); err == nil || !strings.Contains(err.Error(), "generator version") {
		t.Errorf("another generator version must be refused, got %v", err)
	}

	if _, err := ReadManifest(t.TempDir()); err == nil || !strings.Contains(err.Error(), "not a fixture directory") {
		t.Errorf("an empty directory must be refused, got %v", err)
	}
}

// The golden fixture is the reproducibility contract: the data files in
// testdata/golden must be regenerated byte for byte from the spec in their
// manifest, on any machine. A deliberate change to what a spec produces
// bumps Version and regenerates them with `go test ./internal/synth -update`.
func TestTheGoldenFixtureIsReproducedByteForByte(t *testing.T) {
	golden := filepath.Join("testdata", "golden")
	if *update {
		m, err := ReadManifest(golden)
		if err != nil {
			raw, rerr := os.ReadFile(filepath.Join(golden, ManifestFile))
			if rerr != nil {
				t.Fatalf("no golden manifest to regenerate from: %v", rerr)
			}
			if err := json.Unmarshal(raw, &m); err != nil {
				t.Fatal(err)
			}
		}
		if _, err := Write(m.Spec, golden, true); err != nil {
			t.Fatal(err)
		}
		t.Log("regenerated testdata/golden")
	}

	m, err := ReadManifest(golden)
	if err != nil {
		t.Fatalf("golden fixture: %v", err)
	}
	fresh := t.TempDir()
	again, err := Write(m.Spec, fresh, false)
	if err != nil {
		t.Fatal(err)
	}
	if again.Counts != m.Counts {
		t.Errorf("counts %+v, golden %+v", again.Counts, m.Counts)
	}
	for _, name := range []string{UsersFile, PatientsFile, MeasurementsFile} {
		want, _ := os.ReadFile(filepath.Join(golden, name))
		got, _ := os.ReadFile(filepath.Join(fresh, name))
		if !bytes.Equal(want, got) {
			t.Errorf("%s regenerated differently from the golden copy (spec seed %d)", name, m.Spec.Seed)
		}
		if again.Digests[name] != m.Digests[name] {
			t.Errorf("%s digest %s, golden %s", name, again.Digests[name], m.Digests[name])
		}
	}
	// The golden fixture is small on purpose, and it must be an interesting
	// one: readings of more than one type and at least one anomaly.
	if m.Counts.Measurements < 20 || m.Counts.Anomalous == 0 || len(m.Spec.Streams) < 2 {
		t.Errorf("golden fixture is too plain to guard anything: %+v", m.Counts)
	}
	if !m.GeneratedAt.Before(time.Now().Add(time.Minute)) {
		t.Errorf("golden generated_at %s is in the future", m.GeneratedAt)
	}
}
