# Remote state for the environment stacks.
#
# One bucket, one object per environment (environments/<name>/terraform.tfstate),
# each with its own lock. Locking uses S3 itself (use_lockfile in the backend
# block, Terraform 1.10 and later), so there is no DynamoDB table to create,
# pay for or keep consistent.
#
# The bucket is versioned, so a state file damaged by a bad apply can be
# restored from the previous version; encrypted with its own KMS key;
# closed to public access at every level S3 offers; refuses any request
# not made over TLS; and records every request made to it in the access-log
# bucket (logging.tf). prevent_destroy guards the bucket and the key: a
# terraform destroy here would take every environment's state with it.

data "aws_iam_policy_document" "state_key" {
  #checkov:skip=CKV_AWS_109:A key policy. Its resource wildcard means this key only, and this statement is AWS's default policy delegating the key to IAM.
  #checkov:skip=CKV_AWS_111:As CKV_AWS_109.
  #checkov:skip=CKV_AWS_356:As CKV_AWS_109.

  statement {
    sid       = "AccountAdministersThroughIAM"
    actions   = ["kms:*"]
    resources = ["*"]

    principals {
      type        = "AWS"
      identifiers = [local.account_root]
    }
  }
}

resource "aws_kms_key" "state" {
  description             = "VitalMesh Terraform state"
  enable_key_rotation     = true
  deletion_window_in_days = 30
  policy                  = data.aws_iam_policy_document.state_key.json

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_kms_alias" "state" {
  name          = "alias/vitalmesh-terraform-state"
  target_key_id = aws_kms_key.state.key_id
}

resource "aws_s3_bucket" "state" {
  #checkov:skip=CKV_AWS_144:No cross-region replica. Versioning recovers from a bad write, the realistic loss. A regional S3 outage pauses infrastructure changes and touches nothing that is running.
  #checkov:skip=CKV2_AWS_62:Nothing consumes bucket events. Who read or wrote state is recorded by the access logging in logging.tf.

  bucket = local.state_bucket_name

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_s3_bucket_ownership_controls" "state" {
  bucket = aws_s3_bucket.state.id

  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}

resource "aws_s3_bucket_public_access_block" "state" {
  bucket = aws_s3_bucket.state.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "state" {
  bucket = aws_s3_bucket.state.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "state" {
  bucket = aws_s3_bucket.state.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = aws_kms_key.state.arn
    }

    # Caches the data key per bucket, which cuts KMS requests (and their
    # cost) for every state read and lock write.
    bucket_key_enabled = true
  }
}

# Versioning keeps every state file ever written. Ninety days of history is
# ample to recover from a bad apply; beyond that it is storage cost with no
# purpose.
resource "aws_s3_bucket_lifecycle_configuration" "state" {
  bucket = aws_s3_bucket.state.id

  rule {
    id     = "expire-superseded-state"
    status = "Enabled"

    filter {}

    noncurrent_version_expiration {
      noncurrent_days = 90
    }

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }

  depends_on = [aws_s3_bucket_versioning.state]
}

data "aws_iam_policy_document" "state_bucket" {
  statement {
    sid     = "RefuseUnencryptedTransport"
    effect  = "Deny"
    actions = ["s3:*"]
    resources = [
      aws_s3_bucket.state.arn,
      "${aws_s3_bucket.state.arn}/*",
    ]

    principals {
      type        = "*"
      identifiers = ["*"]
    }

    condition {
      test     = "Bool"
      variable = "aws:SecureTransport"
      values   = ["false"]
    }
  }
}

resource "aws_s3_bucket_policy" "state" {
  bucket = aws_s3_bucket.state.id
  policy = data.aws_iam_policy_document.state_bucket.json

  depends_on = [aws_s3_bucket_public_access_block.state]
}

# Every request made to the state bucket: who read an environment's state,
# and who wrote or locked it. State holds no secret values (they are
# write-only, or generated by AWS), but it is a complete map of each
# environment, and reading it deserves an audit trail (section 30).
resource "aws_s3_bucket_logging" "state" {
  bucket        = aws_s3_bucket.state.id
  target_bucket = aws_s3_bucket.access_logs.id
  target_prefix = "state/"

  target_object_key_format {
    partitioned_prefix {
      partition_date_source = "EventTime"
    }
  }

  depends_on = [aws_s3_bucket_policy.access_logs]
}
